import { FullRepository } from 'github-trend';
export default [
    {
        index: 0,
        name: 'SpaceVim',
        owner: 'SpaceVim',
        description: '',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 4929,
        todaysStars: 17,
        forks: 4929,
    },
    {
        index: 1,
        name: 'neovim',
        owner: 'neovim',
        description: 'Vim-fork focused on extensibility and usability',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 25497,
        todaysStars: 16,
        forks: 25497,
    },
    {
        index: 2,
        name: 'vim-plug',
        owner: 'junegunn',
        description: '',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 9564,
        todaysStars: 9,
        forks: 9564,
    },
    {
        index: 3,
        name: 'ale',
        owner: 'w0rp',
        description: 'Asynchronous Lint Engine',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 3809,
        todaysStars: 7,
        forks: 3809,
    },
    {
        index: 4,
        name: 'vim-airline',
        owner: 'vim-airline',
        description: "lean & mean status/tabline for vim that's light as air",
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 10199,
        todaysStars: 7,
        forks: 10199,
    },
    {
        index: 5,
        name: 'vim-fugitive',
        owner: 'tpope',
        description: 'fugitive.vim: a Git wrapper so awesome, it should be illegal',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 9014,
        todaysStars: 5,
        forks: 9014,
    },
    {
        index: 6,
        name: 'tsuquyomi',
        owner: 'Quramy',
        description: 'A Vim plugin for TypeScript',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 625,
        todaysStars: null,
        forks: 625,
    },
    {
        index: 7,
        name: '.vim',
        owner: 'jessfraz',
        description: 'My .vim dotfiles and configurations.',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 304,
        todaysStars: null,
        forks: 304,
    },
    {
        index: 8,
        name: 'minibufexpl.vim',
        owner: 'fholgado',
        description: 'Elegant buffer explorer - takes very little screen space',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 924,
        todaysStars: null,
        forks: 924,
    },
    {
        index: 9,
        name: 'vimplus',
        owner: 'chxuan',
        description: '',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 400,
        todaysStars: null,
        forks: 400,
    },
    {
        index: 10,
        name: 'Vundle.vim',
        owner: 'VundleVim',
        description: 'Vundle, the plug-in manager for Vim',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 16596,
        todaysStars: null,
        forks: 16596,
    },
    {
        index: 11,
        name: 'solarized',
        owner: 'altercation',
        description:
            'precision color scheme for multiple applications (terminal, vim, etc.) with both dark/light modes',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 12045,
        todaysStars: null,
        forks: 12045,
    },
    {
        index: 12,
        name: 'vimrc',
        owner: 'amix',
        description: 'The ultimate Vim configuration: vimrc',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 11675,
        todaysStars: null,
        forks: 11675,
    },
    {
        index: 13,
        name: 'spf13-vim',
        owner: 'spf13',
        description: 'The ultimate vim distribution',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 11604,
        todaysStars: null,
        forks: 11604,
    },
    {
        index: 14,
        name: 'vim-pathogen',
        owner: 'tpope',
        description: 'pathogen.vim: manage your runtimepath',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 9745,
        todaysStars: null,
        forks: 9745,
    },
    {
        index: 15,
        name: 'nerdtree',
        owner: 'scrooloose',
        description: 'A tree explorer plugin for vim.',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 9083,
        todaysStars: null,
        forks: 9083,
    },
    {
        index: 16,
        name: 'syntastic',
        owner: 'vim-syntastic',
        description: 'Syntax checking hacks for vim',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 8737,
        todaysStars: null,
        forks: 8737,
    },
    {
        index: 17,
        name: 'vim-galore',
        owner: 'mhinz',
        description: '',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 7835,
        todaysStars: null,
        forks: 7835,
    },
    {
        index: 18,
        name: 'vim-go',
        owner: 'fatih',
        description: 'Go development plugin for Vim',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 7740,
        todaysStars: null,
        forks: 7740,
    },
    {
        index: 19,
        name: 'janus',
        owner: 'carlhuda',
        description: 'Vim distribution',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 7473,
        todaysStars: null,
        forks: 7473,
    },
    {
        index: 20,
        name: 'ctrlp.vim',
        owner: 'kien',
        description: 'Fuzzy file, buffer, mru, tag, etc finder.',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 5947,
        todaysStars: null,
        forks: 5947,
    },
    {
        index: 21,
        name: 'vim-multiple-cursors',
        owner: 'terryma',
        description: 'True Sublime Text style multiple selections for Vim',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 5768,
        todaysStars: null,
        forks: 5768,
    },
    {
        index: 22,
        name: 'use_vim_as_ide',
        owner: 'yangyangwithgnu',
        description: 'use vim as IDE',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 5528,
        todaysStars: null,
        forks: 5528,
    },
    {
        index: 23,
        name: 'til',
        owner: 'jbranchaud',
        description: '',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 5376,
        todaysStars: null,
        forks: 5376,
    },
    {
        index: 24,
        name: 'vim-surround',
        owner: 'tpope',
        description: 'surround.vim: quoting/parenthesizing made simple',
        language: 'Vim script',
        langColor: '#199f4b',
        allStars: 5165,
        todaysStars: null,
        forks: 5165,
    },
] as FullRepository[];
