import { FullRepository } from 'github-trend';
export default [
    {
        index: 0,
        name: 'yew',
        owner: 'DenisKolodin',
        description: 'Rust framework for making client web apps',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 2930,
        todaysStars: 34,
        forks: 2930,
    },
    {
        index: 1,
        name: 'rust',
        owner: 'rust-lang',
        description: 'A safe, concurrent, practical language.',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 25713,
        todaysStars: 29,
        forks: 25713,
    },
    {
        index: 2,
        name: 'shadertoy-browser',
        owner: 'repi',
        description: 'Shadertoy browser & viewer for Mac built in Rust',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 70,
        todaysStars: 31,
        forks: 70,
    },
    {
        index: 3,
        name: 'alacritty',
        owner: 'jwilm',
        description: 'A cross-platform, GPU-accelerated terminal emulator',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 8374,
        todaysStars: 16,
        forks: 8374,
    },
    {
        index: 4,
        name: 'nanoid',
        owner: 'nikolay-govorov',
        description: 'A tiny, secure, URL-friendly, unique string ID generator for Rust',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 42,
        todaysStars: 12,
        forks: 42,
    },
    {
        index: 5,
        name: 'limn',
        owner: 'christolliday',
        description: 'Cross platform GUI Library',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 253,
        todaysStars: 10,
        forks: 253,
    },
    {
        index: 6,
        name: 'parity',
        owner: 'paritytech',
        description: 'Fast, light, robust Ethereum implementation.',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 3099,
        todaysStars: 9,
        forks: 3099,
    },
    {
        index: 7,
        name: 'Rocket',
        owner: 'SergioBenitez',
        description: 'A web framework for Rust.',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 3460,
        todaysStars: 9,
        forks: 3460,
    },
    {
        index: 8,
        name: 'servo',
        owner: 'servo',
        description: 'The Servo Browser Engine',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 10952,
        todaysStars: 7,
        forks: 10952,
    },
    {
        index: 9,
        name: 'skii',
        owner: 'Piripant',
        description: 'A rust skiing game',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 49,
        todaysStars: 8,
        forks: 49,
    },
    {
        index: 10,
        name: 'zemeroth',
        owner: 'ozkriff',
        description: 'Zemeroth is a 2D turn-based hexagonal strategy game in Rust',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 121,
        todaysStars: 7,
        forks: 121,
    },
    {
        index: 11,
        name: 'stdweb',
        owner: 'koute',
        description: 'A standard library for the client-side Web',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 1102,
        todaysStars: 5,
        forks: 1102,
    },
    {
        index: 12,
        name: 'clap-rs',
        owner: 'kbknapp',
        description: 'A full featured, fast Command Line Argument Parser for Rust',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 1513,
        todaysStars: 6,
        forks: 1513,
    },
    {
        index: 13,
        name: 'artifact',
        owner: 'vitiral',
        description: 'The open source design documentation tool for everybody',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 271,
        todaysStars: 6,
        forks: 271,
    },
    {
        index: 14,
        name: 'fd',
        owner: 'sharkdp',
        description: 'A simple, fast and user-friendly alternative to find.',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 4027,
        todaysStars: 5,
        forks: 4027,
    },
    {
        index: 15,
        name: 'diesel',
        owner: 'diesel-rs',
        description: 'A safe, extensible ORM and Query Builder for Rust',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 2260,
        todaysStars: 5,
        forks: 2260,
    },
    {
        index: 16,
        name: 'book',
        owner: 'rust-lang',
        description: 'The Rust Programming Language',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 1552,
        todaysStars: 5,
        forks: 1552,
    },
    {
        index: 17,
        name: 'gotham',
        owner: 'gotham-rs',
        description:
            'A flexible web framework, built on stable Rust, that does not sacrifice safety, security or speed.',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 564,
        todaysStars: 5,
        forks: 564,
    },
    {
        index: 18,
        name: 'pinky',
        owner: 'koute',
        description: 'An NES emulator written in Rust',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 262,
        todaysStars: 5,
        forks: 262,
    },
    {
        index: 19,
        name: 'three',
        owner: 'three-rs',
        description: 'Totally not inspired Rust 3D library',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 122,
        todaysStars: 5,
        forks: 122,
    },
    {
        index: 20,
        name: 'rust-clippy',
        owner: 'rust-lang-nursery',
        description: 'A bunch of lints to catch common mistakes and improve your Rust code',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 1786,
        todaysStars: null,
        forks: 1786,
    },
    {
        index: 21,
        name: 'cc-rs',
        owner: 'alexcrichton',
        description: 'Rust library for build scripts to compile C/C++ code into a Rust library',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 220,
        todaysStars: null,
        forks: 220,
    },
    {
        index: 22,
        name: 'tools',
        owner: 'amethyst',
        description: 'Game development tools for the Amethyst engine',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 33,
        todaysStars: null,
        forks: 33,
    },
    {
        index: 23,
        name: 'crates.io',
        owner: 'rust-lang',
        description: 'Source code for crates.io',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 680,
        todaysStars: null,
        forks: 680,
    },
    {
        index: 24,
        name: 'gutenberg',
        owner: 'Keats',
        description: 'An opinionated static site generator with everything built-in.',
        language: 'Rust',
        langColor: '#dea584',
        allStars: 744,
        todaysStars: null,
        forks: 744,
    },
] as FullRepository[];
