import { FullRepository } from 'github-trend';
export default [
    {
        index: 0,
        name: 'texttop',
        owner: 'tombh',
        description: 'A fully interactive X Linux desktop rendered in TTY and streamable over SSH',
        language: 'Go',
        langColor: '#375eab',
        allStars: 2910,
        todaysStars: 243,
        forks: 2910,
    },
    {
        index: 1,
        name: 'openebs',
        owner: 'openebs',
        description:
            'OpenEBS is containerized block storage written in Go for cloud native and other environments w/ per container (or pod) QoS SLAs, tiering and replica policies across AZs and environments, and predictable and scalable performance.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 2773,
        todaysStars: 140,
        forks: 2773,
    },
    {
        index: 2,
        name: 'go-ethereum',
        owner: 'ethereum',
        description: 'Official Go implementation of the Ethereum protocol',
        language: 'Go',
        langColor: '#375eab',
        allStars: 11214,
        todaysStars: 56,
        forks: 11214,
    },
    {
        index: 3,
        name: 'go',
        owner: 'golang',
        description: 'The Go programming language',
        language: 'Go',
        langColor: '#375eab',
        allStars: 36232,
        todaysStars: 36,
        forks: 36232,
    },
    {
        index: 4,
        name: 'fireworq',
        owner: 'fireworq',
        description: 'Fireworq is a lightweight, high-performance, language-independent job queue system.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 1376,
        todaysStars: 35,
        forks: 1376,
    },
    {
        index: 5,
        name: 'advanced-go-programming-book',
        owner: 'chai2010',
        description: '',
        language: 'Go',
        langColor: '#375eab',
        allStars: 1052,
        todaysStars: 33,
        forks: 1052,
    },
    {
        index: 6,
        name: 'youjumpijump',
        owner: 'faceair',
        description: '微信跳一跳外挂',
        language: 'Go',
        langColor: '#375eab',
        allStars: 1270,
        todaysStars: 28,
        forks: 1270,
    },
    {
        index: 7,
        name: 'fzf',
        owner: 'junegunn',
        description: '',
        language: 'Go',
        langColor: '#375eab',
        allStars: 12615,
        todaysStars: 30,
        forks: 12615,
    },
    {
        index: 8,
        name: 'Sia',
        owner: 'NebulousLabs',
        description: 'Blockchain-based marketplace for file storage',
        language: 'Go',
        langColor: '#375eab',
        allStars: 2104,
        todaysStars: 28,
        forks: 2104,
    },
    {
        index: 9,
        name: 'awesome-go',
        owner: 'avelino',
        description: 'A curated list of awesome Go frameworks, libraries and software',
        language: 'Go',
        langColor: '#375eab',
        allStars: 26560,
        todaysStars: 26,
        forks: 26560,
    },
    {
        index: 10,
        name: 'kubernetes',
        owner: 'kubernetes',
        description: 'Production-Grade Container Scheduling and Management',
        language: 'Go',
        langColor: '#375eab',
        allStars: 30873,
        todaysStars: 25,
        forks: 30873,
    },
    {
        index: 11,
        name: 'progress',
        owner: 'machinebox',
        description: 'io.Reader and io.Writer with progress and remaining time estimation',
        language: 'Go',
        langColor: '#375eab',
        allStars: 63,
        todaysStars: 25,
        forks: 63,
    },
    {
        index: 12,
        name: 'faas',
        owner: 'openfaas',
        description: 'OpenFaaS - Serverless Functions Made Simple for Docker & Kubernetes',
        language: 'Go',
        langColor: '#375eab',
        allStars: 7976,
        todaysStars: 24,
        forks: 7976,
    },
    {
        index: 13,
        name: 'build-web-application-with-golang',
        owner: 'astaxie',
        description: 'A golang ebook intro how to build a web with golang',
        language: 'Go',
        langColor: '#375eab',
        allStars: 19931,
        todaysStars: 21,
        forks: 19931,
    },
    {
        index: 14,
        name: 'gin',
        owner: 'gin-gonic',
        description:
            'Gin is a HTTP web framework written in Go (Golang). It features a Martini-like API with much better performance -- up to 40 times faster. If you need smashing performance, get yourself some Gin.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 13966,
        todaysStars: 22,
        forks: 13966,
    },
    {
        index: 15,
        name: 'hugo',
        owner: 'gohugoio',
        description: 'The world’s fastest framework for building websites.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 22238,
        todaysStars: 22,
        forks: 22238,
    },
    {
        index: 16,
        name: 'bleve',
        owner: 'blevesearch',
        description: 'A modern text indexing library for go',
        language: 'Go',
        langColor: '#375eab',
        allStars: 3759,
        todaysStars: 18,
        forks: 3759,
    },
    {
        index: 17,
        name: 'istio',
        owner: 'istio',
        description: 'An open platform to connect, manage, and secure microservices.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 5014,
        todaysStars: 18,
        forks: 5014,
    },
    {
        index: 18,
        name: 'perkeep',
        owner: 'perkeep',
        description:
            'Perkeep (née Camlistore) is your personal storage system for life: a way of storing, syncing, sharing, modelling and backing up content.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 2430,
        todaysStars: 18,
        forks: 2430,
    },
    {
        index: 19,
        name: 'fac',
        owner: 'mkchoi212',
        description: 'Easy-to-use CUI for fixing git conflicts',
        language: 'Go',
        langColor: '#375eab',
        allStars: 1193,
        todaysStars: 18,
        forks: 1193,
    },
    {
        index: 20,
        name: 'moby',
        owner: 'moby',
        description:
            'Moby Project - a collaborative project for the container ecosystem to assemble container-based systems',
        language: 'Go',
        langColor: '#375eab',
        allStars: 47125,
        todaysStars: 15,
        forks: 47125,
    },
    {
        index: 21,
        name: 'etcd',
        owner: 'coreos',
        description: 'Distributed reliable key-value store for the most critical data of a distributed system',
        language: 'Go',
        langColor: '#375eab',
        allStars: 16218,
        todaysStars: 13,
        forks: 16218,
    },
    {
        index: 22,
        name: 'capsule8',
        owner: 'capsule8',
        description: 'Capsule8: open-source cloud-native behavioral security monitoring',
        language: 'Go',
        langColor: '#375eab',
        allStars: 154,
        todaysStars: 15,
        forks: 154,
    },
    {
        index: 23,
        name: 'gogs',
        owner: 'gogits',
        description: 'Gogs is a painless self-hosted Git service.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 22561,
        todaysStars: 14,
        forks: 22561,
    },
    {
        index: 24,
        name: 'up',
        owner: 'apex',
        description: 'Deploy infinitely scalable serverless apps, apis, and sites in seconds to AWS.',
        language: 'Go',
        langColor: '#375eab',
        allStars: 4281,
        todaysStars: 14,
        forks: 4281,
    },
] as FullRepository[];
